project_id = "nvvssxykygdxjywncvgd"

[functions.extract-receipt]
verify_jwt = false

[functions.email-import-webhook]
verify_jwt = false

[functions.sync-imap-emails]
verify_jwt = false

[functions.cron-email-sync]
verify_jwt = false

[functions.oauth-start]
verify_jwt = false

[functions.oauth-callback]
verify_jwt = false

[functions.sync-gmail]
verify_jwt = false
