// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-receipts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-receipts.ts
var list_receipts_default = defineTool({
  name: "list_receipts",
  title: "List receipts",
  description: "List the signed-in user's expense receipts, optionally filtered by date range, vendor or status.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Start receipt date (YYYY-MM-DD)."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("End receipt date (YYYY-MM-DD)."),
    vendor: z.string().trim().min(1).optional().describe("Filter by vendor name (partial match)."),
    status: z.string().trim().min(1).optional().describe("Filter by receipt status, e.g. completed."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of receipts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, vendor, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("receipts").select(
      "id, receipt_date, vendor, vendor_brand, description, amount_gross, amount_net, vat_amount, vat_rate, currency, category, tax_type, status, invoice_number"
    ).order("receipt_date", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (from) query = query.gte("receipt_date", from);
    if (to) query = query.lte("receipt_date", to);
    if (vendor) query = query.ilike("vendor", `%${vendor}%`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { receipts: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/expense-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var expense_summary_default = defineTool2({
  name: "expense_summary",
  title: "Expense summary",
  description: "Aggregate the signed-in user's expenses for a period: totals plus breakdown by category and vendor.",
  inputSchema: {
    from: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start receipt date (YYYY-MM-DD)."),
    to: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("End receipt date (YYYY-MM-DD)."),
    group_by: z2.enum(["category", "vendor"]).default("category").describe("Breakdown dimension.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, group_by }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("receipts").select("amount_gross, amount_net, vat_amount, category, vendor, currency").gte("receipt_date", from).lte("receipt_date", to).limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const key = group_by === "vendor" ? "vendor" : "category";
    const groups = {};
    let gross = 0;
    let net = 0;
    let vat = 0;
    for (const row of rows) {
      const g = Number(row.amount_gross ?? 0);
      const n = Number(row.amount_net ?? 0);
      const v = Number(row.vat_amount ?? 0);
      gross += g;
      net += n;
      vat += v;
      const label = row[key] ?? "Ohne Zuordnung";
      const bucket = groups[label] ??= { gross: 0, net: 0, vat: 0, count: 0 };
      bucket.gross += g;
      bucket.net += n;
      bucket.vat += v;
      bucket.count += 1;
    }
    const round = (x) => Math.round(x * 100) / 100;
    const breakdown = Object.entries(groups).map(([label, b]) => ({ label, gross: round(b.gross), net: round(b.net), vat: round(b.vat), count: b.count })).sort((a, b) => b.gross - a.gross);
    const summary = {
      from,
      to,
      group_by: key,
      receipt_count: rows.length,
      total_gross: round(gross),
      total_net: round(net),
      total_vat: round(vat),
      breakdown
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_invoices_default = defineTool3({
  name: "list_invoices",
  title: "List invoices",
  description: "List the signed-in user's outgoing documents (invoices, quotes, orders, delivery notes) with status and totals.",
  inputSchema: {
    status: z3.string().trim().min(1).optional().describe("Filter by status, e.g. draft, sent, paid."),
    document_type: z3.string().trim().min(1).optional().describe("Filter by document type, e.g. invoice, quote."),
    from: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Earliest invoice date (YYYY-MM-DD)."),
    to: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Latest invoice date (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(100).default(25).describe("Maximum number of documents to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, document_type, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("invoices").select(
      "id, invoice_number, document_type, status, invoice_date, due_date, paid_at, subtotal, vat_total, total, currency, customer_id"
    ).order("invoice_date", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    if (document_type) query = query.eq("document_type", document_type);
    if (from) query = query.gte("invoice_date", from);
    if (to) query = query.lte("invoice_date", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { invoices: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_vendors_default = defineTool4({
  name: "list_vendors",
  title: "List vendors",
  description: "List the signed-in user's vendors with receipt counts and accumulated totals.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Filter by vendor display name (partial match)."),
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of vendors to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("vendors").select("id, display_name, receipt_count, total_amount, default_vat_rate, default_tax_type, website").order("receipt_count", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (search) query = query.ilike("display_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vendors: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_customers_default = defineTool5({
  name: "list_customers",
  title: "List customers",
  description: "List the signed-in user's customers with contact and billing defaults.",
  inputSchema: {
    search: z5.string().trim().min(1).optional().describe("Filter by display name (partial match)."),
    include_archived: z5.boolean().default(false).describe("Include archived customers."),
    limit: z5.number().int().min(1).max(100).default(50).describe("Maximum number of customers to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("customers").select(
      "id, display_name, company_name, contact_person, email, phone, city, country, customer_number, payment_terms_days, default_currency, is_archived"
    ).order("display_name", { ascending: true }).limit(limit ?? 50);
    if (!include_archived) query = query.eq("is_archived", false);
    if (search) query = query.ilike("display_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nvvssxykygdxjywncvgd";
var mcp_default = defineMcp({
  name: "billmonk",
  title: "BillMonk",
  version: "0.1.0",
  instructions: "Tools for BillMonk, a document management and accounting automation app. Read the signed-in user's receipts, expense summaries, outgoing invoices, vendors and customers. All amounts are stored gross/net/VAT per receipt; prefer `expense_summary` for aggregated reporting over summing `list_receipts` yourself.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_receipts_default, expense_summary_default, list_invoices_default, list_vendors_default, list_customers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
